version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "src/aitrainer-test-client/package.json"
      - "src/aitrainer-test-client/package-lock.json"
