services:
  webapi:
    build:
      context: .
      dockerfile: src/AiTrainer.Web/dockerfile
    ports:
      - 5222:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+8080
      ConnectionStrings__DefaultConnection: Server=postgres;Port=5432;Database=ai_trainer;User ID=postgres;Password=postgres;SslMode=Disable
      ClientSettings__AuthorityHost: https://aitrainer.oidc:443
      ClientSettings__UserInfoEndpoint: https://aitrainer.oidc:443/connect/userinfo
    depends_on:
      - "postgres"
