volumes:
  postgres_data: {}

services:
  postgres:
    container_name: ai-trainer.db
    image: postgres:17-alpine
    ports:
      - 5560:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ai_trainer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  oidc:
    container_name: oidc-server-mock
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - "44363:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:443;http://+90
      ASPNETCORE_HTTP_PORT: 44363
      USERS_CONFIGURATION_PATH: /tmp/config/users.json
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
      SERVER_OPTIONS_INLINE: |
        {
         "IssuerUri": "http://localhost:44363"
        }
    volumes:
      - ./mocks/oidc:/tmp/config:ro
