FROM node

WORKDIR /app


COPY src/AiTrainer.Core/ /app
COPY src/AiTrainer.Core/package.json /app
COPY src/AiTrainer.Core/src/Data/*.json ./src/Data/



RUN npm install

RUN npm run build


CMD ["node", "build/index.js"]