FROM node

WORKDIR /app


COPY src/AiTrainer.Core/ /app
COPY src/AiTrainer.Core/package.json /app
COPY src/AiTrainer.Core/package-lock.json /app
COPY src/AiTrainer.Core/src/Data/*.json ./src/Data/



RUN npm ci

RUN npm run build


CMD ["npm", "start"]