services:
  webapi:
    build:
      context: .
      dockerfile: src/AiTrainer.Web/dockerfile
    ports:
      - 5222:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+80
      ConnectionStrings__DefaultConnection: Server=postgres;Port=5432;Database=ai_trainer;User ID=postgres;Password=postgres;SslMode=Disable
      ClientSettings__InternalUserInfoEndpoint: http://oidc:80/connect/userinfo
      ClientSettings__InternalAuthorityHost: http://oidc:80
      ClientSettings__AuthorityClientId: aitrainer-k6-local
      AiTrainerCore__BaseEndpoint: http://coreapi:4000
    depends_on:
      - "postgres"
