[assembly: System.Reflection.AssemblyCompanyAttribute("AiTrainer.Web.Api")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+abb2ed20b9fb1589118e585124855126b6f02b1c")]
[assembly: System.Reflection.AssemblyProductAttribute("AiTrainer.Web.Api")]
[assembly: System.Reflection.AssemblyTitleAttribute("AiTrainer.Web.Api")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]