FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS base

RUN apk add --no-cache icu-libs
RUN apk add --no-cache icu-data-full

RUN adduser --uid 10000 runner --disabled-password
USER 10000

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS publish
ARG CONF=Release

WORKDIR /src

COPY src/AiTrainer.Web/AiTrainer.Web.Api/*.csproj ./AiTrainer.Web/AiTrainer.Web.Api/
COPY src/AiTrainer.Web/AiTrainer.Web.Api.SignalR/*.csproj ./AiTrainer.Web/AiTrainer.Web.Api.SignalR/
COPY src/AiTrainer.Web/AiTrainer.Web.Common/*.csproj ./AiTrainer.Web/AiTrainer.Web.Common/
COPY src/AiTrainer.Web/AiTrainer.Web.CoreClient/*.csproj ./AiTrainer.Web/AiTrainer.Web.CoreClient/
COPY src/AiTrainer.Web/AiTrainer.Web.Persistence/*.csproj ./AiTrainer.Web/AiTrainer.Web.Persistence/
COPY src/AiTrainer.Web/AiTrainer.Web.Domain.Models/*.csproj ./AiTrainer.Web/AiTrainer.Web.Domain.Models/
COPY src/AiTrainer.Web/AiTrainer.Web.Domain.Services/*.csproj ./AiTrainer.Web/AiTrainer.Web.Domain.Services/
COPY src/AiTrainer.Web/AiTrainer.Web.UserInfoClient/*.csproj ./AiTrainer.Web/AiTrainer.Web.UserInfoClient/
COPY src/Submodules/BT/src/BT.Common/BT.Common.FastArray/*.csproj ./Submodules/BT/src/BT.Common/BT.Common.FastArray/
COPY src/Submodules/BT/src/BT.Common/BT.Common.OperationTimer/*.csproj ./Submodules/BT/src/BT.Common/BT.Common.OperationTimer/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Helpers/*.csproj ./Submodules/BT/src/BT.Common/BT.Common.Helpers/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Http/*.csproj ./Submodules/BT/src/BT.Common/BT.Common.Http/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Polly/*.csproj ./Submodules/BT/src/BT.Common/BT.Common.Polly/

RUN dotnet restore AiTrainer.Web/AiTrainer.Web.Api/AiTrainer.Web.Api.csproj 

COPY src/AiTrainer.Web/AiTrainer.Web.Api/ ./AiTrainer.Web/AiTrainer.Web.Api/
COPY src/AiTrainer.Web/AiTrainer.Web.Api.SignalR/ ./AiTrainer.Web/AiTrainer.Web.Api.SignalR/
COPY src/AiTrainer.Web/AiTrainer.Web.Common/ ./AiTrainer.Web/AiTrainer.Web.Common/
COPY src/AiTrainer.Web/AiTrainer.Web.CoreClient/ ./AiTrainer.Web/AiTrainer.Web.CoreClient/
COPY src/AiTrainer.Web/AiTrainer.Web.Persistence/ ./AiTrainer.Web/AiTrainer.Web.Persistence/
COPY src/AiTrainer.Web/AiTrainer.Web.Domain.Models/ ./AiTrainer.Web/AiTrainer.Web.Domain.Models/
COPY src/AiTrainer.Web/AiTrainer.Web.Domain.Services/ ./AiTrainer.Web/AiTrainer.Web.Domain.Services/
COPY src/AiTrainer.Web/AiTrainer.Web.UserInfoClient/ ./AiTrainer.Web/AiTrainer.Web.UserInfoClient/
COPY src/Submodules/BT/src/BT.Common/BT.Common.FastArray/ ./Submodules/BT/src/BT.Common/BT.Common.FastArray/
COPY src/Submodules/BT/src/BT.Common/BT.Common.OperationTimer/ ./Submodules/BT/src/BT.Common/BT.Common.OperationTimer/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Helpers/ ./Submodules/BT/src/BT.Common/BT.Common.Helpers/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Http/ ./Submodules/BT/src/BT.Common/BT.Common.Http/
COPY src/Submodules/BT/src/BT.Common/BT.Common.Polly/ ./Submodules/BT/src/BT.Common/BT.Common.Polly/

WORKDIR /src/AiTrainer.Web/AiTrainer.Web.Api
ARG CONF=Release
RUN dotnet publish AiTrainer.Web.Api.csproj -c ${CONF} -o /app

FROM base AS final
ARG CONF=Release
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "AiTrainer.Web.Api.dll"]